### ISSUE TITLE
Does not clear layers

### ISSUE THREAD

**Issue by qayshp** [keyboardio/Kaleidoscope-Escape-OneShot#7] opened 2018-05-25 04:32 UTC
The escape key properly clears modifiers, but I don't currently see a way to have it clear layers. Sorry if I missed something.

I know this may not be ideal as, by default, the escape key on FUNCTION layer is mapped to a mouse key, but it would be nice to have a way to clear the OSL macro as well as the OSM macro.

**Comment by algernon** [comment] 2018-05-25 04:46
It *should* be clearing layers too, because it uses `OneShot.cancel()` which doesn't make a difference, and cancels everything.

I'll look into it.

**Comment by algernon** [comment] 2018-06-17 15:02
I can't reproduce the problem. Can you perhaps share your sketch?

**Comment by joeynguyen** [comment] 2018-07-05 15:39
I have this same issue as well.  Escape clears the modifier but not the sticky layer for me.

For example, on my Mac, I can escape the modifiers using Escape after pressing Alt and Command.  However, if Alt and Command are sticky and I press Escape, it triggers the Mac's Alt+Command+Escape functionality instead of clearing the modifier.

My sketch:
https://github.com/joeynguyen/dotfiles/blob/1dd3c3827a05172f901b83f0423649529ac315bb/Model01-Firmware/Model01-Firmware.ino

**Comment by joeynguyen** [comment] 2018-07-05 17:15
Could I be that I'm on an older version of the firmware?

**Comment by algernon** [comment] 2018-07-05 18:16
It's never a bad idea to try the current git master. O:)

**Comment by joeynguyen** [comment] 2018-07-09 21:18
I updated to the latest version of the firmware (1.23).  The Escape key still doesn't cancel out sticky layer.

In regards to your comment, "It should be clearing layers too, because it uses OneShot.cancel() which doesn't make a difference, and cancels everything."  Maybe I'm wrong, but according to OneShot documentation, shouldn't it use `OneShot.cancel(true)` to clear out the sticky layer?

**Comment by TreTuna** [comment] 2018-07-11 09:06
I'm having this same issue. It's clearing non-sticky OneShots, but not sticky ones. I'm on current git master. My sketch is at https://github.com/TreTuna/Model01-Firmware/blob/master/Model01-Firmware.ino

**Comment by algernon** [comment] 2018-07-25 06:42
> Maybe I'm wrong, but according to OneShot documentation, shouldn't it use `OneShot.cancel(true)` to clear out the sticky layer?

[It does](https://github.com/keyboardio/Kaleidoscope-Escape-OneShot/blob/24d298d459b27ec6cc380702695a352b26aefbed/src/Kaleidoscope/Escape-OneShot.cpp#L36).

I'll try to look into this issue this coming Friday. Apologies for the delay!

**Comment by altosaar** [comment] 2018-10-05 22:01
Also not working for me on Mac (Mojave; latest)

**Comment by algernon** [comment] 2018-10-18 05:57
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#408.

**Closed** 2018-10-18 05:57 UTC
Labels: bug
